import {useEffect, useId, useMemo, useRef, useState} from 'react';
import {Box, Camera, Check, ChevronRight, Crosshair, GitBranch, LoaderCircle, Search, Trash2} from 'lucide-react';
import {api} from './api';
import type {Building, Entity, GraphData, Identification, Issue, Link, PlanningInputs, Simulation} from './types';
import {actionLabels} from './types';

export function ElementPicker({building,roomId='',system='',value,onChange,onFocus}:{building:Building;roomId?:string;system?:string;value:string|null;onChange:(id:string|null)=>void;onFocus?:(id:string)=>void}){
 const [query,setQuery]=useState(''),[items,setItems]=useState<(Entity&{distanceMetres:number})[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const [floor,setFloor]=useState(building.entities.find(e=>e.id===roomId)?.floorId||'');
 useEffect(()=>{setFloor(building.entities.find(e=>e.id===roomId)?.floorId||'');},[roomId,building]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);const timer=setTimeout(()=>{
   const params=new URLSearchParams({q:query,roomId,system,floor,limit:'30'});
   api<{items:(Entity&{distanceMetres:number})[];total:number}>(`/api/elements?${params}`,{signal:abort.signal}).then(r=>{setItems(r.items);setTotal(r.total);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});
 },200);return()=>{clearTimeout(timer);abort.abort();};},[query,floor,roomId,system]);
 const current=building.entities.find(e=>e.id===value);
 return <div className="element-picker"><div className="element-search"><Search size={15}/><input aria-label="Search model elements" placeholder="IFC ID, tag, pipe / 风管 / 阀门…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <select aria-label="Element level" value={floor} onChange={e=>setFloor(e.target.value)}><option value="">All levels</option>{building.floors.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select>
 {current&&<div className="picked-element"><Check size={14}/><span>{current.name}<small>{current.ifcType} · {current.ifcGlobalId}</small></span><button type="button" onClick={()=>onChange(null)}>Clear</button></div>}
 <small>{loading?'Searching…':`${total} matching elements · showing first 30`}</small>{error&&<p role="alert">{error}</p>}
 <div className="element-results">{items.map(e=><button type="button" className={value===e.id?'picked':''} key={e.id} onClick={()=>{onChange(e.id);onFocus?.(e.id);}}><Box size={14}/><span><strong>{e.name}</strong><small>{e.ifcType} · {e.floorName||e.floorId}{roomId?` · ${e.distanceMetres} m from room bounds`:''}</small><code>{e.ifcGlobalId||e.id}</code></span><ChevronRight size={14}/></button>)}</div>
 <p className="helper-text">Every result is an individual model element. Distance helps locate it; it does not establish service connectivity.</p></div>;
}

export function SuggestionList({result,onChoose}:{result:Identification;onChoose:(id:string)=>void}){return <div className="identification-result"><strong>{result.mode==='vision'?'Photo observations':'Text location suggestions'}</strong>{result.observations?.map((s,i)=><p key={i}>{s}</p>)}{result.possibleProblems?.length? <p>Possible problems: {result.possibleProblems.join('; ')}</p>:null}{result.candidates.map(c=><button type="button" className="suggested-element" key={c.assetId} onClick={()=>onChoose(c.assetId)}><Crosshair size={14}/><span>{c.name}<small>{c.ifcType} · {c.basis}</small></span></button>)}{!result.candidates.length&&<p>No uniquely supported element was identified. Choose the element manually, or keep the room-level location.</p>}<small>{result.note}</small>{result.missingEvidence?.map((s,i)=><p key={i}>To check: {s}</p>)}</div>;}

export function IssueLocation({issue,building,selectedId,onSelect,onUpdated}:{issue:Issue;building:Building;selectedId:string|null;onSelect:(id:string)=>void;onUpdated:(issue:Issue)=>void}){
 const [asset,setAsset]=useState(issue.assetId||null),[detail,setDetail]=useState(issue.locationDetail||''),[result,setResult]=useState<Identification|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{setAsset(issue.assetId||null);setDetail(issue.locationDetail||'');},[issue.assetId,issue.locationDetail]);
 const identify=async(photos:boolean)=>{setBusy('identify');setError('');try{const r=await api<Identification>(`/api/issues/${issue.id}/identify`,{method:'POST',body:JSON.stringify({usePhotos:photos})});if(alive.current)setResult(r);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy('');}};
 const save=async()=>{setBusy('save');setError('');try{const updated=await api<Issue>(`/api/issues/${issue.id}/location`,{method:'PUT',body:JSON.stringify({assetId:asset,locationDetail:detail})});if(alive.current)onUpdated(updated);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy('');}};
 const selected=building.entities.find(e=>e.id===selectedId&&e.kind!=='room');
 return <details className="location-editor" open={!issue.assetId}><summary><Crosshair size={15}/>Exact reported location {issue.assetId?'· linked':'· room only'}</summary>
 <p className="helper-text">Red means a reported location. Confirming a location does not confirm a root cause.</p>
 <label className="field-label">Where on the component?<input value={detail} maxLength={1000} onChange={e=>setDetail(e.target.value)} placeholder="e.g. joint above the bedroom door / 卧室门上方接头"/></label>
 {selected&&<button className="button secondary full" onClick={()=>setAsset(selected.id)}>Use 3D selection: {selected.ifcType}</button>}
 <ElementPicker building={building} roomId={issue.roomId} value={asset} onChange={setAsset} onFocus={onSelect}/>
 <div className="feature-actions"><button className="button secondary compact" disabled={!!busy} onClick={()=>void identify(false)}>Read description</button><button className="button secondary compact" disabled={!!busy||!issue.photos.length} onClick={()=>void identify(true)}><Camera size={14}/>Inspect photos</button></div>
 {result&&<SuggestionList result={result} onChoose={id=>{setAsset(id);onSelect(id);}}/>}{error&&<p className="feature-error" role="alert">{error}</p>}
 <button className="button primary full" disabled={!!busy} onClick={()=>void save()}>{busy?<LoaderCircle size={15} className="spin"/>:<Check size={15}/>}Save reported location</button><p className="helper-text">Changing the location requires a new analysis. Previous saved records remain stored.</p></details>;
}

export function GraphView({graph,title='Evidence graph',onNode}:{graph:GraphData;title?:string;onNode?:(id:string)=>void}){
 const marker=useId().replace(/:/g,'');
 const positions=useMemo(()=>{
  const levels=new Map(graph.nodes.map(n=>[n.id,0]));
  for(let i=0;i<graph.nodes.length;i++){let changed=false;for(const e of graph.edges){const next=Math.min(graph.nodes.length-1,(levels.get(e.source)||0)+1);if(next>(levels.get(e.target)||0)){levels.set(e.target,next);changed=true;}}if(!changed)break;}
  const columns=new Map<number,number>();return new Map(graph.nodes.map(n=>{const level=levels.get(n.id)||0,row=columns.get(level)||0;columns.set(level,row+1);return [n.id,{x:18+level*205,y:22+row*120}];}));
 },[graph]);
 const width=Math.max(390,...[...positions.values()].map(p=>p.x+190)),height=Math.max(145,...[...positions.values()].map(p=>p.y+110));
 return <div className="graph-card"><strong><GitBranch size={14}/>{title}</strong><div className="graph-scroll"><svg viewBox={`0 0 ${width} ${height}`} width={width} height={height} role="img" aria-label={title}><defs><marker id={marker} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7 Z" fill="#608883"/></marker></defs>{graph.edges.map(e=>{const a=positions.get(e.source),b=positions.get(e.target);if(!a||!b)return null;return <g key={e.id}><path d={`M${a.x+175},${a.y+40} C${a.x+190},${a.y+40} ${b.x-18},${b.y+40} ${b.x-3},${b.y+40}`} fill="none" stroke="#608883" strokeWidth="1.5" markerEnd={`url(#${marker})`}/><title>{e.relation}</title></g>;})}{graph.nodes.map(n=>{const p=positions.get(n.id)!;return <g key={n.id}><rect x={p.x} y={p.y} width="175" height="84" rx="7" fill={n.kind==='RootCause'?'#fff0d5':'#f0f7f5'} stroke={n.kind==='RootCause'?'#d9a243':'#abc9c4'}/><foreignObject x={p.x+9} y={p.y+7} width="157" height="70"><div className="graph-node"><small>{n.kind}</small><button type="button" onClick={()=>onNode?.(n.id)}>{n.label}</button></div></foreignObject></g>;})}</svg></div><div className="graph-edge-labels">{[...new Set(graph.edges.map(e=>e.relation))].join(' · ')}</div></div>;
}

export function KnowledgeStatus(){
 const [summary,setSummary]=useState<{backend:string;nodeCount:number;edgeCount:number;rowCount?:number;failuresWithoutCauses?:number;warnings?:string[]}|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{const c=new AbortController();api<typeof summary>('/api/knowledge/summary',{signal:c.signal}).then(setSummary).catch(e=>{if(e.name!=='AbortError')setMessage(e.message);});return()=>c.abort();},[]);
 return <details className="knowledge-status"><summary><GitBranch size={14}/>{summary?.backend==='neo4j'?'Neo4j graph queries':summary?.backend==='neo4j-csv-snapshot'?'Imported causal graph · local snapshot':'Knowledge status'}</summary>{summary&&<><p>{summary.nodeCount} nodes · {summary.edgeCount} relationships</p>{summary.failuresWithoutCauses!==undefined&&<p>{summary.failuresWithoutCauses} failure modes have no exported root-cause links.</p>}<ul>{summary.warnings?.map(w=><li key={w}>{w}</li>)}</ul></>}<button className="text-button" onClick={()=>{void api<{connected:boolean;importedNodes:number;expectedNodes:number}>('/api/knowledge/connection',{method:'POST'}).then(r=>setMessage(`Connected: ${r.importedNodes}/${r.expectedNodes} dataset nodes imported.`)).catch(e=>setMessage(e.message));}}>Check configured Neo4j connection</button>{message&&<p role="status">{message}</p>}</details>;
}

const states=['ventilation_loss','cooling_loss','heating_loss','power_loss','water_loss'];
export function TopologyEditor({building,selectedId,onSelect}:{building:Building;selectedId:string|null;onSelect:(id:string)=>void}){
 const [links,setLinks]=useState<Link[]>([]),[source,setSource]=useState(''),[target,setTarget]=useState(''),[relation,setRelation]=useState('SERVES'),[required,setRequired]=useState('ventilation_loss'),[produced,setProduced]=useState('ventilation_loss'),[basis,setBasis]=useState<'assumption'|'verified'>('assumption'),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();api<Link[]>('/api/topology',{signal:c.signal}).then(setLinks).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[]);
 const label=(id:string)=>building.entities.find(e=>e.id===id)?.name||id;
 const selected=building.entities.find(e=>e.id===selectedId);
 const save=async()=>{setBusy(true);setError('');try{await api<Link>('/api/topology',{method:'POST',body:JSON.stringify({sourceId:source,targetId:target,relation,requires:required,produces:produced,basis,note})});setLinks(await api<Link[]>('/api/topology'));setNote('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <details className="topology-editor"><summary><GitBranch size={15}/>Service connections · {links.length}</summary><p className="helper-text">Define directed dependencies using drawings or inspection evidence. Assumed links stay labelled. Re-run analysis after edits to use the updated topology.</p>
 <div className="link-endpoint"><strong>From: {source?label(source):'Choose an element in 3D or the catalogue'}</strong><button className="text-button" disabled={!selected||selected.kind==='room'} onClick={()=>selected&&setSource(selected.id)}>Use selected element as source</button></div>
 <div className="link-endpoint"><strong>To: {target?label(target):'Choose a room or another element'}</strong><button className="text-button" disabled={!selected} onClick={()=>{if(selected){setTarget(selected.id);setRelation(selected.kind==='room'?'SERVES':'FEEDS');}}}>Use current selection as target</button><select aria-label="Service target room" value={building.entities.some(e=>e.id===target&&e.kind==='room')?target:''} onChange={e=>{setTarget(e.target.value);setRelation('SERVES');}}><option value="">Or choose a served room…</option>{building.entities.filter(e=>e.kind==='room').map(e=><option value={e.id} key={e.id}>{e.name} · {e.floorName||e.floorId}</option>)}</select></div>
 <div className="form-grid"><label className="field-label">Relationship<select value={relation} onChange={e=>setRelation(e.target.value)}>{['SERVES','FEEDS','SUPPLIES_POWER','CONNECTED_TO'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field-label">Evidence status<select value={basis} onChange={e=>setBasis(e.target.value as typeof basis)}><option value="assumption">Assumed</option><option value="verified">Verified by maintenance</option></select></label><label className="field-label">When source loses<select value={required} onChange={e=>setRequired(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select></label><label className="field-label">Target loses<select value={produced} onChange={e=>setProduced(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select></label></div><label className="field-label">Drawing / inspection reference or assumption<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2} maxLength={2000}/></label><button className="button primary full" disabled={busy||!source||!target||note.trim().length<5} onClick={()=>void save()}>Save directed connection</button>{error&&<p role="alert" className="feature-error">{error}</p>}
 <div className="topology-links">{links.map(link=><div key={link.id}><button onClick={()=>onSelect(link.sourceId)}>{label(link.sourceId)}</button> → <button onClick={()=>onSelect(link.targetId)}>{label(link.targetId)}</button><small>{link.relation} · {link.requires} → {link.produces} · {link.basis}<br/>{link.note}</small><button title="Remove connection" aria-label="Remove connection" onClick={()=>{void api(`/api/topology/${link.id}`,{method:'DELETE'}).then(()=>setLinks(old=>old.filter(l=>l.id!==link.id))).catch(e=>setError(e.message));}}><Trash2 size={13}/></button></div>)}</div></details>;
}

export function PlanningControls({value,onChange,selectedId,building,action,hideBasic=false}:{value:PlanningInputs;onChange:(v:PlanningInputs)=>void;selectedId:string|null;building:Building;action:Simulation['action'];hideBasic?:boolean}){
 const number=(key:keyof PlanningInputs,label:string,min:number,max:number,step=1)=><label className="field-label" key={key}>{label}<input type="number" min={min} max={max} step={step} value={value[key] as number} onChange={e=>onChange({...value,[key]:e.target.valueAsNumber})}/></label>;
 const selected=building.entities.find(e=>e.id===selectedId&&e.kind!=='room');
 return <div className="planning-controls"><p className="helper-text">Editable planning assumptions. Default hours and prices are illustrative.</p><div className="form-grid">{!hideBasic&&number('durationHours','Work duration (h)',.25,168,.25)}{!hideBasic&&number('workers','Crew size',1,50)}{number('hourlyRate','Hourly rate / person',0,10000)}{!hideBasic&&number('materialCost','Materials cost',0,1000000)}<label className="field-label">Currency<select value={value.currency} onChange={e=>onChange({...value,currency:e.target.value})}>{['SGD','EUR','USD','CNY'].map(c=><option key={c}>{c}</option>)}</select></label>{number('uncertaintyPercent','Cost range ± (%)',0,100)}{number('occupantsPerRoom','Assumed occupants / room',0,200)}<label className="field-label">Service lost<select value={value.serviceState} onChange={e=>onChange({...value,serviceState:e.target.value})}>{states.map(s=><option key={s}>{s}</option>)}</select></label>{number('horizonHours','Planning horizon (h)',1,168)}</div>
 {action==='system_shutdown'&&<div className="isolation-picker"><strong>Isolation: {building.entities.find(e=>e.id===value.isolationAssetId)?.name||'Select an upstream component'}</strong><button className="button secondary compact" disabled={!selected} onClick={()=>selected&&onChange({...value,isolationAssetId:selected.id})}>Use current 3D selection</button><small>The component must reach the candidate via entered conditional service links.</small></div>}
 <label className="field-label">Materials / specification assumption<textarea value={value.materialDescription} maxLength={1000} onChange={e=>onChange({...value,materialDescription:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={value.roomClosure} onChange={e=>onChange({...value,roomClosure:e.target.checked})}/>Plan room closure during outage</label><label className="check-label"><input type="checkbox" checked={value.coolingUnavailable} onChange={e=>onChange({...value,coolingUnavailable:e.target.checked})}/>Assume cooling is unavailable in affected rooms</label>
 {value.coolingUnavailable&&<details open><summary>Temperature scenario inputs</summary><p className="helper-text">Uncalibrated first-order air-temperature model. Shared inputs apply to each affected room; ventilation loss alone does not imply cooling loss.</p><div className="form-grid">{number('initialTemperature','Initial room temperature (°C)',-10,50,.5)}{number('outdoorTemperature','Outdoor temperature (°C)',-30,55,.5)}{number('internalGainWatts','Internal heat gains (W)',0,10000)}{number('conductanceWattsPerK','Heat conductance UA (W/K)',10,5000)}{number('capacitanceKwhPerK','Thermal capacitance (kWh/K)',.1,200,.1)}{number('recoveryHours','Recovery time constant (h)',.25,48,.25)}{number('comfortUpper','User comfort threshold (°C)',15,40,.5)}</div></details>}</div>;
}

export function SimulationMetrics({simulation,building,printMode=false}:{simulation:Simulation;building:Building;printMode?:boolean}){
 const r=simulation.resources,curve=simulation.roomImpacts?.find(r=>r.comfort)?.comfort;
 if(!r)return null;
 const points=curve?.points||[],min=Math.min(...points.map(p=>p.temperature),curve?.threshold||24)-1,max=Math.max(...points.map(p=>p.temperature),curve?.threshold||28)+1;
 const x=(h:number)=>42+h/(points.at(-1)?.hour||24)*294,y=(t:number)=>145-(t-min)/(max-min)*120;
 return <div className="simulation-metrics"><div className="resource-grid"><div><strong>{r.currency} {r.totalCost.toFixed(0)}</strong><small>{r.lowCost.toFixed(0)}–{r.highCost.toFixed(0)} estimated range</small></div><div><strong>{r.workers} people · {r.workHours} h</strong><small>{r.personHours} person-hours · {r.outageHours} h service interruption</small></div></div><small>{r.basis}</small>
 {simulation.solutionGraph&&<GraphView graph={simulation.solutionGraph} title="Repair plan → conditional outcome"/>}
 {simulation.roomImpacts?.map(i=><div className="room-impact" key={i.roomId}><strong>{building.entities.find(e=>e.id===i.roomId)?.name||i.roomId}</strong><span>{i.availability} · {i.hours} h</span><small>{i.services.join(', ')} · {i.basis}</small></div>)}
 {curve&&<div className="thermal-chart"><strong>Illustrative air temperature · °C</strong><svg viewBox="0 0 360 180" role="img" aria-label="Assumed room air temperature over the planning horizon"><path d="M42 20 V145 H342" fill="none" stroke="#a1b2ad"/><path d={`M42 ${y(curve.threshold)} H342`} stroke="#b99444" strokeDasharray="4 4"/><polyline fill="none" stroke="#cf6454" strokeWidth="2.5" points={points.map(p=>`${x(p.hour)},${y(p.temperature)}`).join(' ')}/><text x="4" y="28">{max.toFixed(1)}</text><text x="4" y="148">{min.toFixed(1)}</text><text x="40" y="165">0 h</text><text x="291" y="165">{points.at(-1)?.hour} h</text><text x="190" y={y(curve.threshold)-5}>Threshold {curve.threshold}°</text></svg><p>Peak {curve.peakTemperature.toFixed(1)} °C · {curve.hoursAboveThreshold} h above your threshold.</p><small>{curve.method}<br/>{curve.basis}</small></div>}
 <details className="notice-drafts" open={printMode}><summary>Occupant notice drafts · not sent</summary>{simulation.occupantNotices?.map(n=><article key={n.roomId}><p>{n.en}</p><p>{n.zh}</p><button className="text-button" onClick={()=>{void navigator.clipboard?.writeText(n.en+'\n'+n.zh);}}>Copy notice</button></article>)}</details></div>;
}

export function ScenarioComparison({items,onSelect}:{items:Simulation[];onSelect:(id:string)=>void}){
 const rows=items.filter(s=>s.resources).slice(0,12);
 if(rows.length<2)return null;
 return <div className="scenario-comparison"><h4>Compare saved scenarios</h4><div className="table-scroll"><table><thead><tr><th>Plan</th><th>Cost estimate</th><th>Crew / work</th><th>Rooms / outage</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><button onClick={()=>onSelect(s.id)}>{actionLabels[s.action]}</button></td><td>{s.resources!.currency} {s.resources!.totalCost}</td><td>{s.resources!.workers} / {s.resources!.workHours} h</td><td>{s.during.affectedRoomIds.length} / {s.resources!.outageHours} h</td></tr>)}</tbody></table></div><small>Compare assumptions as well as cost. Scenarios may use different candidate causes.</small></div>;
}
