import {useEffect, useState} from 'react';
import {ArrowRight, MessageCircle, Send, ShieldCheck, Sparkles} from 'lucide-react';
import {Brand, EvidenceList, Notice} from './App';
import {api} from './api';
import type {Evidence, Issue} from './types';
import {statusLabels} from './types';
import './studio.css';

export function ResidentAssistant({embeddedIssueId}:{embeddedIssueId?:string}){
 const issueId=embeddedIssueId||new URLSearchParams(location.search).get('issueId');
 const [issue,setIssue]=useState<Issue|null>(null),[messages,setMessages]=useState<{role:string;text:string;note?:string;sources?:Evidence[]}[]>([]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!issueId)return;const c=new AbortController();api<Issue>(`/api/issues/${issueId}`,{signal:c.signal}).then(setIssue).catch(e=>e.name!=='AbortError'&&setError(e.message));return()=>c.abort();},[issueId]);
 const send=async(text=question)=>{if(!text.trim()||busy)return;setQuestion('');setError('');setBusy(true);setMessages(m=>[...m,{role:'user',text}]);try{const r=await api<{answer:string;note:string;sources:Evidence[]}>('/api/resident/chat',{method:'POST',body:JSON.stringify({issueId:issueId||undefined,message:text})});setMessages(m=>[...m,{role:'assistant',text:r.answer,note:r.note,sources:r.sources}]);}catch(e){setError((e as Error).message);setQuestion(text);}finally{setBusy(false);}};
 const content=<><div className="resident-assistant-intro"><span className="assistant-orb"><MessageCircle size={28}/></span><span className="eyebrow">BUILDING 1 / RESIDENT SUPPORT</span><h1>A little help,<br/>right where you are.</h1><p>Describe what you notice, check your report, and find simple steps while the team investigates.</p><span className="guidance-label"><ShieldCheck size={14}/>Guided demo · English / 中文 · no LLM required</span></div>{issue&&<div className="resident-case"><span className={`status ${issue.status}`}>{statusLabels[issue.status]}</span><strong>{issue.title}</strong><small>This conversation only uses the linked report’s information.</small></div>}<div className="resident-prompts">{['The air feels stuffy. What can I do for now?','维修期间我还能使用这个房间吗？','What is the status of my report?'].map(q=><button key={q} onClick={()=>void send(q)} disabled={busy}>{q}<ArrowRight size={15}/></button>)}</div><div className="resident-conversation" aria-live="polite">{messages.map((m,i)=><article key={i} className={`resident-message ${m.role}`}><span className="eyebrow">{m.role==='user'?'YOU / 您':'BUILDING CARE'}</span><p>{m.text}</p>{m.note&&<small>{m.note}</small>}{m.sources&&<EvidenceList items={m.sources}/>}</article>)}{busy&&<p className="helper-text">Reading your report…</p>}</div>{error&&<Notice error>{error}</Notice>}<form className="resident-chat-form" onSubmit={e=>{e.preventDefault();void send();}}><textarea aria-label="Resident question" rows={3} maxLength={3000} placeholder="What’s happening in your room? / 您的房间有什么问题？" value={question} onChange={e=>setQuestion(e.target.value)}/><button className="button primary" disabled={busy||!question.trim()} type="submit"><Send size={16}/>Send</button></form><p className="helper-text"><Sparkles size={13}/>Preset guidance and saved case information. Equipment diagnosis and repairs remain with maintenance staff. Draft scenarios are not published outage commitments.</p><a className="button secondary full" href="/report">Report an issue / 上报问题<ArrowRight size={16}/></a></>;
 return embeddedIssueId?<section className="resident-assistant-embedded">{content}</section>:<div className="resident-shell"><header className="resident-header"><Brand/><a href="/report" className="text-button">Report an issue<ArrowRight size={14}/></a></header><main className="resident-assistant-main">{content}</main></div>;
}
