import {useEffect, useMemo, useRef, useState} from 'react';
import {ArrowLeft, Check, Crosshair, FileText, LoaderCircle, Pause, Play, RefreshCw} from 'lucide-react';
import {api} from './api';
import {Brand, EvidenceList, Notice, shortName, WorkspaceMenu} from './App';
import ModelViewer from './ModelViewer';
import KnowledgeGraph from './KnowledgeGraph';
import {ElementPicker, IssueLocation, PlanningControls} from './Features';
import {ComparisonCharts, scenarioName, TraceGraph} from './Visuals';
import {defaultPlanning, statusLabels} from './types';
import type {Analysis, Building, Candidate, GraphData, Issue, PlanningInputs, RepairPlan, Simulation} from './types';
import './studio.css';

const inspectionLabels={untested:'Not checked',investigating:'Checking',ruled_out:'Ruled out',confirmed:'Confirmed'};
const planLabel=(r:RepairPlan)=>r.action==='observe'?'Monitor':r.action==='system_shutdown'?'Isolate branch & repair':r.method==='replace'?'Replace component':'Local repair';

export function Studio({issueId}:{issueId:string}){
  const [building,setBuilding]=useState<Building|null>(null),[issue,setIssue]=useState<Issue|null>(null),[analysis,setAnalysis]=useState<Analysis|null>(null),[sims,setSims]=useState<Simulation[]>([]);
  const [candidateId,setCandidateId]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null),[floor,setFloor]=useState('all'),[focus,setFocus]=useState({id:null as string|null,tick:0});
  const [error,setError]=useState(''),[busy,setBusy]=useState(''),[observations,setObservations]=useState(''),[editObservations,setEditObservations]=useState(false);
  const [inspection,setInspection]=useState<NonNullable<Candidate['inspection']>['status']>('investigating'),[note,setNote]=useState(''),[bindId,setBindId]=useState<string|null>(null);
  const [trace,setTrace]=useState<(GraphData&{note:string;connected:boolean})|null>(null),[recipes,setRecipes]=useState<RepairPlan[]>([]),[planIndex,setPlanIndex]=useState(1),[parameters,setParameters]=useState<PlanningInputs>({...defaultPlanning});
  const [simulationId,setSimulationId]=useState(''),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[fitTick,setFitTick]=useState(0),[inspectOpen,setInspectOpen]=useState(false);
  const resultRef=useRef<HTMLElement>(null),candidate=analysis?.candidates.find(c=>c.id===candidateId);
  const currentSims=sims.filter(s=>s.causeId===candidateId),simulation=currentSims.find(s=>s.id===simulationId),frames=simulation?.animation?.frames||[],frame=frames[step];
  const entities=useMemo(()=>new Map(building?.entities.map(e=>[e.id,e])||[]),[building]);
  const label=(id:string)=>shortName(entities.get(id)?.name||id);
  const scopeFloor=(ids:string[])=>{const levels=[...new Set(ids.map(id=>entities.get(id)?.floorId).filter(Boolean))];return levels.length===1?levels[0] as string:'all';};
  const select=(id:string)=>{const e=entities.get(id);if(e){setSelectedId(id);setFloor(e.floorId);setFocus(f=>({id,tick:f.tick+1}));}};
  const run=async(name:string,fn:()=>Promise<void>)=>{setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
  const applyAnalysis=(a:Analysis)=>{setAnalysis(a);setCandidateId(old=>a.candidates.some(c=>c.id===old)?old:a.candidates[0]?.id||'');setSims([]);setSimulationId('');setPlaying(false);setStep(0);setNote('');};
  useEffect(()=>{const c=new AbortController();Promise.all([api<Building>('/api/building',{signal:c.signal}),api<Issue>(`/api/issues/${issueId}`,{signal:c.signal}),api<Analysis|null>(`/api/issues/${issueId}/analysis`,{signal:c.signal}),api<Simulation[]>(`/api/issues/${issueId}/simulations`,{signal:c.signal})]).then(([b,i,a,s])=>{setBuilding(b);setIssue(i);setAnalysis(a);setCandidateId(a?.candidates.find(c=>c.inspection?.status==='confirmed')?.id||a?.candidates[0]?.id||'');setObservations(a?.observations||'');setSims(s.filter(s=>s.analysisId===a?.id));setSelectedId(i.assetId||i.roomId);setFloor(b.entities.find(e=>e.id===i.roomId)?.floorId||'all');setFocus({id:i.roomId,tick:1});}).catch(e=>e.name!=='AbortError'&&setError(e.message));return()=>c.abort();},[issueId]);
  useEffect(()=>{setTrace(null);setRecipes([]);setNote('');setBindId(candidate?.assetId||null);setInspection(candidate?.inspection?.status||'investigating');setInspectOpen(false);if(!candidateId||!analysis)return;const c=new AbortController();Promise.all([api<GraphData&{note:string;connected:boolean}>(`/api/issues/${issueId}/trace?causeId=${encodeURIComponent(candidateId)}`,{signal:c.signal}),api<{plans:RepairPlan[]}>(`/api/issues/${issueId}/plans?causeId=${encodeURIComponent(candidateId)}`,{signal:c.signal})]).then(([t,r])=>{setTrace(t);setFitTick(v=>v+1);setRecipes(r.plans);const i=r.plans.length>1?1:0,p=r.plans[i];setPlanIndex(i);setParameters({...defaultPlanning,...p?.defaults,repairMethod:p?.method||'standard',materialDescription:p?.materials.join('; ')||'No repair materials',serviceState:issue?.system==='electrical'?'power_loss':'ventilation_loss'});}).catch(e=>e.name!=='AbortError'&&setError(e.message));return()=>c.abort();},[candidateId,analysis?.id]);
  useEffect(()=>{if(!playing||!frames.length)return;const timer=setInterval(()=>setStep(s=>{if(s>=frames.length-1){setPlaying(false);return s;}return s+1;}),1900);return()=>clearInterval(timer);},[playing,frames.length]);
  const analyze=()=>void run('analysis',async()=>{const a=await api<Analysis>(`/api/issues/${issueId}/analysis`,{method:'POST',body:JSON.stringify({observations})});applyAnalysis(a);setEditObservations(false);});
  const inspect=()=>void run('inspection',async()=>{const a=await api<Analysis>(`/api/issues/${issueId}/inspections`,{method:'POST',body:JSON.stringify({analysisId:analysis!.id,causeId:candidateId,status:inspection,note})});applyAnalysis(a);setInspectOpen(false);});
  const bind=()=>void run('bind',async()=>{const a=await api<Analysis>(`/api/issues/${issueId}/bindings`,{method:'POST',body:JSON.stringify({analysisId:analysis!.id,causeId:candidateId,assetId:bindId,reason:note})});applyAnalysis(a);});
  const changeCandidate=(id:string)=>{if(busy||id===candidateId)return;setCandidateId(id);setSimulationId('');setPlaying(false);const c=analysis?.candidates.find(c=>c.id===id);if(c?.assetId){setSelectedId(c.assetId);setFloor(entities.get(c.assetId)?.floorId||floor);}};
  const choosePlan=(index:number)=>{setSimulationId('');setPlaying(false);setPlanIndex(index);const r=recipes[index];setParameters(p=>({...p,...r.defaults,repairMethod:r.method,materialDescription:r.materials.join('; ')||'No repair materials',isolationAssetId:r.action==='system_shutdown'?issue?.demoContext?.fanId||null:null}));};
  const simulate=()=>void run('scenario',async()=>{const r=recipes[planIndex];const s=await api<Simulation>(`/api/issues/${issueId}/simulations`,{method:'POST',body:JSON.stringify({analysisId:analysis!.id,causeId:candidateId,action:r.action,parameters})});setSims(old=>[s,...old]);setSimulationId(s.id);setStep(0);setPlaying(true);setFloor(scopeFloor([...s.during.affectedAssetIds,...s.during.affectedRoomIds]));setFitTick(t=>t+1);requestAnimationFrame(()=>resultRef.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'}));});
  const showSimulation=(id:string)=>{const s=currentSims.find(s=>s.id===id);setSimulationId(id);setPlaying(false);if(s){const fs=s.animation?.frames||[];setStep(Math.max(0,fs.map(f=>f.phase).lastIndexOf('during')));if(s.parameters)setParameters(s.parameters);const index=recipes.findIndex(r=>r.action===s.action&&r.method===(s.parameters?.repairMethod||'standard'));if(index>=0)setPlanIndex(index);setFloor(scopeFloor([...s.during.affectedAssetIds,...s.during.affectedRoomIds]));setFitTick(t=>t+1);}};
  const updateLocation=(i:Issue)=>{setIssue(i);setAnalysis(null);setSims([]);setSimulationId('');setCandidateId('');setTrace(null);setPlaying(false);select(i.assetId||i.roomId);};
  const contextIds=simulation?[...simulation.during.affectedAssetIds,...simulation.during.affectedRoomIds]:trace?.nodes.map(n=>n.id)||[];
  const impact=simulation?(frame?.impact||simulation.during):null,restored=simulation&&frame?.phase==='after'&&simulation.action!=='observe';
  const physicalGraph:GraphData=simulation?{nodes:contextIds.map(id=>({id,label:label(id),kind:entities.get(id)?.kind==='room'?'Room':id===issue?.assetId?'Reported':'Element'})),edges:(analysis?.topologySnapshot||[]).filter(e=>contextIds.includes(e.sourceId)&&contextIds.includes(e.targetId)&&simulation.during.paths.some(p=>p.nodes.some((n,i)=>n===e.sourceId&&p.nodes[i+1]===e.targetId))&&simulation.during.serviceStates?.[e.sourceId]?.includes(e.requires)&&simulation.during.serviceStates?.[e.targetId]?.includes(e.produces)).map(e=>({id:e.id,source:e.sourceId,target:e.targetId,relation:e.relation,basis:e.basis,condition:e.requires+' → '+e.produces,note:e.note}))}:{nodes:[],edges:[]};
  const numeric=(key:'durationHours'|'workers'|'materialCost',title:string,min:number,step=1)=><label className="field-label">{title}<input type="number" min={min} step={step} value={parameters[key]} onChange={e=>{setSimulationId('');setPlaying(false);setParameters(p=>({...p,[key]:e.target.valueAsNumber}));}}/></label>;
  const selectedPlan=recipes[planIndex];
  return <div className="clear-workspace investigation-workspace">
    <header className="clear-header"><Brand/><a className="clear-back" href="/"><ArrowLeft size={14}/>All issues</a><div className="clear-header-actions"><a className="button secondary compact" href={`/reports/${issueId}${simulationId?'?simulationId='+simulationId:''}`} target="_blank" rel="noreferrer"><FileText size={14}/>Report</a><WorkspaceMenu issueId={issueId}/></div></header>
    {!building||!issue?<main className="startup-state">{error?<Notice error>{error}</Notice>:<><LoaderCircle className="spin"/><p>Loading investigation…</p></>}</main>:<>
      <div className="clear-case-bar"><div><h1>{issue.title.replace('[CASE STUDY] ','')}</h1><div><button onClick={()=>select(issue.roomId)}>{label(issue.roomId)}</button><span>·</span><button onClick={()=>select(issue.assetId||issue.roomId)}>{issue.assetId?label(issue.assetId):'Room-level report'}</button>{issue.isDemo&&<span className="demo-tag">Demo case</span>}</div></div><select aria-label="Issue status" value={issue.status} disabled={!!busy} onChange={e=>{const status=e.target.value;void run('status',async()=>setIssue(await api<Issue>(`/api/issues/${issueId}`,{method:'PATCH',body:JSON.stringify({status})})));}}>{Object.entries(statusLabels).map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></div>
      <main className="clear-layout investigation-layout">
        <div className="clear-model"><ModelViewer compact serviceMode building={building} selectedId={selectedId} onSelect={select} focus={focus} floor={floor} setFloor={setFloor} impact={impact} phase={frame?.phase||'during'} reportedIds={restored?[]:[issue.assetId||issue.roomId]} suspectIds={!simulation&&candidate?.inspection?.status!=='ruled_out'?candidate?.assetIds||[]:[]} restoredIds={restored?contextIds:[]} contextIds={contextIds} fitContextTick={fitTick}/>
          <div className="clear-model-tools"><span>{simulation?'Impact preview':'Reported location in red'}</span><button className="text-button" onClick={()=>{setFloor(scopeFloor(contextIds));setFitTick(t=>t+1);}} disabled={!contextIds.length}><Crosshair size={13}/>Fit related elements</button></div>
          {simulation&&frames.length>0&&<div className="clear-playback"><button className="play-toggle" aria-label={playing?'Pause animation':'Play animation'} onClick={()=>{if(step>=frames.length-2)setStep(0);setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>}</button><div><strong>{frame?.label}</strong><input aria-label="Propagation step" type="range" min="0" max={frames.length-1} value={step} onChange={e=>{setPlaying(false);setStep(+e.target.value);}}/></div><small>{step+1}/{frames.length}</small><button className="muted-button" onClick={()=>{setSimulationId('');setPlaying(false);}}>Return to diagnosis</button></div>}
          <details className="clear-report-details"><summary>Report & location details</summary><p>{issue.description}</p>{issue.locationDetail&&<p>{issue.locationDetail}</p>}{issue.photos.length>0&&<div className="issue-photos">{issue.photos.map(p=><a href={p.url} target="_blank" rel="noreferrer" key={p.id}><img src={p.url} alt={p.name}/></a>)}</div>}<IssueLocation key={issue.id} issue={issue} building={building} selectedId={selectedId} onSelect={select} onUpdated={updateLocation}/></details>
        </div>
        <div className="clear-work investigation-panel">
          {error&&<Notice error>{error}</Notice>}
          <section className="clear-section diagnosis-section"><div className="section-heading"><h2>Possible causes</h2>{analysis&&<button className="muted-button" onClick={()=>setEditObservations(!editObservations)}><RefreshCw size={12}/>Update analysis</button>}</div>
            {(!analysis||editObservations)&&<div className="clear-analyze"><label className="field-label">Additional observations<textarea value={observations} rows={2} onChange={e=>setObservations(e.target.value)} placeholder="What was observed on site?"/></label><button className="button primary compact" onClick={analyze} disabled={!!busy}>{busy==='analysis'?<LoaderCircle className="spin" size={14}/>:null}{analysis?'Update graph search':'Find possible causes'}</button></div>}
            {analysis&&<><div className="cause-selection"><label className="field-label"><span>{analysis.candidates.length} candidates</span><select aria-label="Candidate cause" value={candidateId} onChange={e=>changeCandidate(e.target.value)} disabled={!!busy}>{analysis.candidates.map((c,i)=><option key={c.id} value={c.id}>{i+1}. {c.label}{c.inspection?' · '+inspectionLabels[c.inspection.status]:''}</option>)}</select></label>{candidate&&<span className={`inspection-badge ${candidate.inspection?.status||'untested'}`}>{inspectionLabels[candidate.inspection?.status||'untested']}</span>}</div>
              <KnowledgeGraph analysis={analysis} candidate={candidate} onCandidate={changeCandidate}/>
              {!analysis.candidates.length&&<Notice>No candidate matched this report. Add observations or review graph coverage.</Notice>}
              {candidate&&<><div className="clear-inspect-line"><span>{candidate.assetId?<button className="location-link" onClick={()=>select(candidate.assetId!)}><Crosshair size={13}/>{label(candidate.assetId)}</button>:'Model component not yet linked'}</span><button className="text-button" onClick={()=>setInspectOpen(!inspectOpen)} aria-expanded={inspectOpen}>{candidate.inspection?'Review inspection':'Record inspection'}</button></div>
                <p className="clear-checks"><strong>Check:</strong> {candidate.checks.join(' · ')||'No check specified in this dataset.'}</p>
                {inspectOpen&&<div className="clear-inspection"><label className="field-label">Inspection evidence<textarea aria-label="Inspection evidence" rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="What was checked and what was found"/></label><div className="inspection-actions"><label className="field-label">Conclusion<select aria-label="Inspection conclusion" value={inspection} onChange={e=>setInspection(e.target.value as typeof inspection)}>{Object.entries(inspectionLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="button primary compact" onClick={inspect} disabled={!!busy||note.trim().length<5}><Check size={14}/>Save inspection</button></div>{candidate.inspection&&<p className="saved-inspection">{candidate.inspection.note}</p>}<small>Saving evidence creates a new analysis; rerun scenarios for the updated diagnosis.</small></div>}
                <details className="quiet-details"><summary>Evidence & component mapping</summary><p>{candidate.reason}</p><p>{candidate.mappingBasis}</p>{candidate.missingEvidence?.length? <ul>{candidate.missingEvidence.map(m=><li key={m}>{m}</li>)}</ul>:null}{trace&&<TraceGraph graph={{...trace,nodes:trace.nodes.map(n=>({...n,label:shortName(n.label)}))}} title="Building connections" onSelect={select}/>}<p>{trace?.note}</p><details><summary>Change linked component</summary><ElementPicker building={building} roomId={issue.roomId} value={bindId} onChange={setBindId} onFocus={select}/><button className="text-button" disabled={!selectedId||entities.get(selectedId)?.kind==='room'} onClick={()=>setBindId(selectedId)}>Use 3D selection</button><label className="field-label">Reason<textarea value={note} onChange={e=>setNote(e.target.value)} rows={2}/></label><button className="button secondary compact" onClick={bind} disabled={!!busy||!bindId||note.trim().length<5}>Save component association</button></details><EvidenceList items={candidate.evidence}/>{analysis.queryTrace&&<details className="query-trace"><summary>Graph query · {analysis.queryTrace.backend}</summary><pre>{analysis.queryTrace.query}</pre><pre>{JSON.stringify(analysis.queryTrace.parameters,null,2)}</pre></details>}</details>
              </>}
            </>}
          </section>
          {candidate&&<section className="clear-section repair-section"><div className="section-heading"><h2>Repair options</h2><small>{candidate.inspection?.status==='confirmed'?'Inspector-confirmed cause':'Planning for an unconfirmed cause'}</small></div>
            {candidate.inspection?.status==='ruled_out'?<p className="quiet-empty">This cause was ruled out. Select another candidate above.</p>:!candidate.assetId?<p className="quiet-empty">Link a model component under “Evidence & component mapping” before simulating.</p>:<>{!recipes.length?<p className="muted">Loading repair options…</p>:<><div className="clear-plan-list" role="radiogroup" aria-label="Repair option">{recipes.map((r,i)=><button role="radio" aria-checked={i===planIndex} key={r.action+r.method} className={i===planIndex?'selected':''} onClick={()=>choosePlan(i)} disabled={!!busy}><span className="plan-radio"/><strong>{planLabel(r)}</strong><span>{i===planIndex?parameters.durationHours:r.defaults.durationHours} h · {i===planIndex?parameters.workers:r.defaults.workers} {(i===planIndex?parameters.workers:r.defaults.workers)===1?'person':'people'}</span><b>{parameters.currency} {(i===planIndex?parameters.workers*parameters.durationHours*parameters.hourlyRate+parameters.materialCost:(r.defaults.workers||1)*(r.defaults.durationHours||1)*parameters.hourlyRate+(r.defaults.materialCost||0)).toLocaleString()}</b></button>)}</div>
              {selectedPlan&&<><p className="clear-tradeoff">{selectedPlan.tradeoff}</p><div className="clear-basic-inputs">{numeric('durationHours','Work hours',.25,.25)}{numeric('workers','People',1)}{numeric('materialCost',`Materials (${parameters.currency})`,0)}</div><details className="quiet-details clear-assumptions"><summary>Materials, service & comfort assumptions</summary><PlanningControls hideBasic value={parameters} onChange={p=>{setSimulationId('');setPlaying(false);setParameters(p);}} selectedId={selectedId} building={building} action={selectedPlan.action}/></details>{selectedPlan.action==='system_shutdown'&&<div className="isolation-notice">Isolation: {parameters.isolationAssetId?label(parameters.isolationAssetId):'Choose an upstream element in the assumptions above'}</div>}<div className="clear-run"><span><strong>{parameters.currency} {(parameters.workers*parameters.durationHours*parameters.hourlyRate+parameters.materialCost).toLocaleString()}</strong><small>Planning estimate · editable assumptions</small></span><button className="button primary" onClick={simulate} disabled={!!busy||!candidate.assetId||(selectedPlan.action==='system_shutdown'&&!parameters.isolationAssetId)||Object.values(parameters).some(v=>typeof v==='number'&&!Number.isFinite(v))}>{busy==='scenario'?<LoaderCircle className="spin" size={15}/>:<Play size={15}/>}Simulate impact</button></div></>}
            </>}</>}
          </section>}
          {currentSims.length>0&&<section className="clear-section impact-section" ref={resultRef}><div className="section-heading"><h2>Impact</h2><small>{currentSims.length} saved scenarios</small></div><select className="saved-scenario-select" aria-label="Saved scenario" value={simulationId} onChange={e=>showSimulation(e.target.value)}><option value="">Choose a saved result</option>{currentSims.map((s,i)=><option key={s.id} value={s.id}>{scenarioName(s)} · {s.resources?.workHours} h · {s.resources?.currency} {s.resources?.totalCost} {i===0?'(latest)':''}</option>)}</select>
            {simulation&&<><div className="clear-impact-kpis"><div><strong>{simulation.during.affectedRoomIds.length}</strong><span>affected rooms</span></div><div><strong>{simulation.resources?.outageHours} h</strong><span>service interruption</span></div><div><strong>{simulation.metrics?.affectedOccupants??'—'}</strong><span>assumed occupants</span></div></div><div className="clear-room-list">{simulation.roomImpacts?.map(r=><button key={r.roomId} onClick={()=>select(r.roomId)}><span>{label(r.roomId)}</span><small>{r.availability} · {r.hours} h</small></button>)}</div><p className="clear-impact-basis">{issue.isDemo?'Demo service connections. ':''}Restoration assumes successful repair.</p><details className="quiet-details"><summary>Propagation & repair sequence</summary><TraceGraph graph={physicalGraph} title="Service dependencies" onSelect={select} activeIds={impact?[...impact.affectedRoomIds,...impact.affectedAssetIds]:undefined} animated={playing}/>{simulation.solutionGraph&&<TraceGraph graph={simulation.solutionGraph} title="Repair sequence"/>}<p>{simulation.animation?.basis}</p></details><details className="quiet-details"><summary>Resident notice drafts</summary>{simulation.occupantNotices?.map(n=><article key={n.roomId}><p>{n.en}</p><p>{n.zh}</p></article>)}<small>Drafts only · not sent</small></details></>}
            <details className="quiet-details clear-comparison"><summary>Compare saved scenarios</summary><ComparisonCharts compact items={currentSims} onSelect={showSimulation} selectedId={simulationId}/></details>
          </section>}
        </div>
      </main>
    </>}
  </div>;
}
