import {useId, useMemo, useState} from 'react';
import type {GraphData, Simulation} from './types';
import {actionLabels} from './types';

const colors:Record<string,string>={Reported:'#c84d51',RootCause:'#b17924',Candidate:'#b17924',FailureMode:'#5475a2',Equipment:'#357d7a',DiagnosticCheck:'#6d65a5',Room:'#7b63a0',Element:'#357d7a',Action:'#357d7a',Hypothesis:'#b17924',Outcome:'#357d7a'};
export function TraceGraph({graph,title,onSelect,activeIds,animated=false}:{graph:GraphData;title:string;onSelect?:(id:string)=>void;activeIds?:string[];animated?:boolean}){
 const marker=useId().replace(/:/g,''),[detail,setDetail]=useState('');
 const sequence=graph.edges.length>0&&graph.edges.every(e=>e.relation==='PLANNED_NEXT');
 const pos=useMemo(()=>{
  if(sequence)return new Map(graph.nodes.map((n,i)=>[n.id,{x:20+(Math.floor(i/3)%2?2-i%3:i%3)*290,y:24+Math.floor(i/3)*145}]));
  const incoming=new Set(graph.edges.map(e=>e.target));const levels=new Map<string,number>();const queue=graph.nodes.filter(n=>!incoming.has(n.id)).map(n=>n.id);if(!queue.length&&graph.nodes.length)queue.push(graph.nodes[0].id);queue.forEach(id=>levels.set(id,0));
  for(let i=0;i<queue.length;i++){const id=queue[i];for(const e of graph.edges.filter(e=>e.source===id)){if(!levels.has(e.target)){levels.set(e.target,(levels.get(id)||0)+1);queue.push(e.target);}}}
  const rows=new Map<number,number>();return new Map(graph.nodes.map(n=>{const col=levels.get(n.id)||0,row=rows.get(col)||0;rows.set(col,row+1);return[n.id,{x:20+col*290,y:24+row*140}];}));
 },[graph,sequence]);
 const width=Math.max(580,...[...pos.values()].map(p=>p.x+220)),height=Math.max(158,...[...pos.values()].map(p=>p.y+118));
 return <section className={`trace-graph ${animated?'flowing':''}`}><div className="visual-heading"><h3>{title}</h3><span>{graph.nodes.length} nodes / {graph.edges.length} links</span></div><div className="trace-scroll"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={title} style={{minWidth:Math.min(width,650)}}><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#8eaaa5"/></marker></defs>{graph.edges.map(e=>{const a=pos.get(e.source),b=pos.get(e.target);if(!a||!b)return null;const active=!activeIds||activeIds.includes(e.source)&&activeIds.includes(e.target);const vertical=sequence&&a.y!==b.y,reverse=sequence&&b.x<a.x;const ax=vertical?a.x+100:reverse?a.x:a.x+200,ay=vertical?a.y+100:a.y+49,bx=vertical?b.x+100:reverse?b.x+206:b.x-6,by=vertical?b.y-6:b.y+49;const labelX=(ax+bx)/2,labelY=(ay+by)/2-17;return <g key={e.id} opacity={active?1:.18}><path className={active&&animated?'flow-edge':''} d={vertical?`M${ax},${ay}L${bx},${by}`:`M${ax},${ay}C${ax+(reverse?-45:45)},${ay} ${bx+(reverse?45:-45)},${by} ${bx},${by}`}  fill="none" stroke="#8eaaa5" strokeWidth="2" strokeDasharray={e.basis==='assumption'?'5 5':undefined} markerEnd={`url(#${marker})`}/><g role="button" tabIndex={0} onClick={()=>setDetail(`${e.relation} · ${e.condition||'Knowledge association'} · ${e.basis||'Imported KG'} ${e.note||''}`)} onKeyDown={k=>k.key==='Enter'&&setDetail(e.condition||e.relation)}><rect x={labelX-42} y={labelY-15} width="85" height="24" rx="6" fill="#f2f6f4"/><text x={labelX} y={labelY+1} textAnchor="middle" fontSize="9" fill="#496e68">{e.relation.replace('HAS_','')}</text><title>{e.relation} {e.condition} {e.note}</title></g></g>;})}{graph.nodes.map(n=>{const p=pos.get(n.id)!,color=colors[n.kind]||'#357d7a',active=!activeIds||activeIds.includes(n.id);return <g key={n.id} opacity={active?1:.28}><rect x={p.x} y={p.y} width="200" height="100" rx="12" fill="white" stroke={color} strokeWidth="1.5"/><rect x={p.x} y={p.y+16} width="4" height="65" rx="2" fill={color}/><foreignObject x={p.x+13} y={p.y+11} width="174" height="82"><div className="trace-node"><span style={{color}}>{n.kind.replace(/([a-z])([A-Z])/g,'$1 $2')}</span><button onClick={()=>{setDetail(`${n.label} · ${n.id}`);onSelect?.(n.id);}} title={n.label}>{n.label}</button></div></foreignObject></g>;})}</svg></div><p className="trace-detail" role="status">{detail||'Select a node to inspect it; select a relationship to read its meaning. Dashed links are assumptions.'}</p></section>;
}

const seriesColors=['#168f83','#e39448','#667dc7','#be667f','#5e948b','#ad965c'];
export const scenarioName=(s:Simulation)=>s.plan?.label||actionLabels[s.action];
export function ComparisonCharts({items,onSelect,selectedId,compact=false}:{items:Simulation[];onSelect:(id:string)=>void;selectedId:string;compact?:boolean}){
 const [hover,setHover]=useState<number|null>(null);
 const rows=items.filter(s=>s.resources).slice(0,6).reverse();
 const currencies=new Set(rows.map(s=>s.resources!.currency));
 const thermal=rows.filter(s=>s.roomImpacts?.some(r=>r.comfort));
 const curves=thermal.map(s=>({s,c:s.roomImpacts!.find(r=>r.comfort)!.comfort!}));
 const xmax=Math.max(24,...curves.map(c=>c.c.points.at(-1)?.hour||24));
 const ymin=Math.floor(Math.min(24,...curves.flatMap(c=>c.c.points.map(p=>p.temperature))))-1,ymax=Math.ceil(Math.max(30,...curves.flatMap(c=>c.c.points.map(p=>p.temperature))));
 const x=(h:number)=>58+h/xmax*640,y=(t:number)=>240-(t-ymin)/(ymax-ymin)*210;
 const maxCost=Math.max(1,...rows.map(s=>s.resources!.highCost)),maxBurden=Math.max(1,...rows.map(s=>s.metrics?.occupantServiceHours||0));
 if(!rows.length)return <div className="studio-empty">Run a repair scenario to build your comparison. Saved values remain traceable to their analysis and input assumptions.</div>;
 return <div className={`comparison-charts ${compact?'compact-comparison':''}`}>{!compact&&<div className="visual-heading"><div><h2>Compare scenarios</h2></div><span>{rows.length} saved scenarios</span></div>}<div className="scenario-key">{rows.map((s,i)=><button key={s.id} className={selectedId===s.id?'selected':''} onClick={()=>onSelect(s.id)}><i style={{background:seriesColors[i]}}/>{scenarioName(s)}<small>{s.diagnosisStatus||'Hypothesis'}</small></button>)}</div>
 <div className="chart-pair"><section className="metric-chart"><h3>Resource commitment</h3><p>Estimated cost {currencies.size===1?`· ${rows[0].resources!.currency}`:'· mixed currencies (no common cost scale)'}</p>{rows.map((s,i)=><div className="bar-row" key={s.id}><div><span>{scenarioName(s)}</span><strong>{s.resources!.currency} {s.resources!.totalCost.toLocaleString()}</strong></div>{currencies.size===1&&<div className="bar-track"><i style={{width:`${s.resources!.totalCost/maxCost*100}%`,background:seriesColors[i]}}/><span className="cost-range" style={{left:`${s.resources!.lowCost/maxCost*100}%`,width:`${(s.resources!.highCost-s.resources!.lowCost)/maxCost*100}%`}}/></div>}<small>{s.resources!.workers} people × {s.resources!.workHours} h · materials {s.resources!.materialCost} · ±{s.parameters?.uncertaintyPercent}%</small></div>)}</section><section className="metric-chart"><h3>Resident disruption</h3><p>Assumed occupant-hours of service loss</p>{rows.map((s,i)=><div className="bar-row" key={s.id}><div><span>{scenarioName(s)}</span><strong>{s.metrics?.occupantServiceHours??'—'} h</strong></div><div className="bar-track"><i style={{width:`${(s.metrics?.occupantServiceHours||0)/maxBurden*100}%`,background:seriesColors[i]}}/></div><small>{s.during.affectedRoomIds.length} rooms · {s.metrics?.affectedOccupants??'—'} assumed occupants · {s.resources!.outageHours} h interruption</small></div>)}</section></div>
 {curves.length>0?<section className="temperature-compare"><div className="visual-heading"><h3>Thermal recovery over time</h3><span>ILLUSTRATIVE AIR TEMPERATURE / °C</span></div><svg viewBox="0 0 740 286" role="img" aria-label="Comparison of assumed indoor air temperature for saved repair scenarios" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(xmax,((e.clientX-r.left)/r.width*740-58)/640*xmax)));}} onMouseLeave={()=>setHover(null)}>{Array.from({length:5},(_,i)=>{const t=ymin+(ymax-ymin)*i/4;return <g key={i}><path d={`M58 ${y(t)}H698`} stroke="#e4ece8"/><text x="42" y={y(t)+4} textAnchor="end">{t.toFixed(0)}°</text></g>;})}{Array.from({length:5},(_,i)=>{const h=xmax*i/4;return <text key={i} x={x(h)} y="264" textAnchor="middle">{h.toFixed(0)} h</text>;})}{[...new Set(curves.map(c=>c.c.threshold))].map(t=><g key={t}><path d={`M58 ${y(t)}H698`} stroke="#c4a55c" strokeDasharray="5 5"/><text x="694" y={y(t)-6} textAnchor="end">User threshold {t}°</text></g>)}{curves.map(({s,c})=><polyline key={s.id} fill="none" stroke={seriesColors[rows.indexOf(s)]} strokeWidth="3" points={c.points.map(p=>`${x(p.hour)},${y(p.temperature)}`).join(' ')}/>)}{hover!==null&&<path d={`M${x(hover)} 22V241`} stroke="#183b39" strokeDasharray="3 3"/>}</svg>{hover!==null&&<div className="curve-tooltip">At {hover.toFixed(1)} h {curves.map(({s,c})=>{const near=c.points.reduce((a,b)=>Math.abs(a.hour-hover)<Math.abs(b.hour-hover)?a:b);return <span key={s.id} style={{color:seriesColors[rows.indexOf(s)]}}>{scenarioName(s)}: {near.temperature.toFixed(1)}°C</span>;})}</div>}<p className="helper-text">Cooling loss must be explicitly assumed. Shared room inputs; constant weather and heat gains. Air temperature is not operative temperature, PMV or PPD. Different inputs and causes can change comparability.</p></section>:<section className="studio-empty">No thermal forecast has been requested. Enable “Assume cooling is unavailable” only when appropriate to your scenario.</section>}
 <div className="table-scroll"><table className="decision-table"><thead><tr><th>Scenario</th><th>Service availability¹</th><th>Room closure</th><th>Heat exposure²</th><th>Peak air temp.</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{scenarioName(s)}</td><td>{s.metrics?.serviceAvailabilityPercent??'—'}%</td><td>{s.metrics?.roomClosureHours??'—'} room·h</td><td>{s.metrics?.temperatureDegreeHoursPerRoom??'—'} °C·h / room</td><td>{s.roomImpacts?.find(r=>r.comfort)?.comfort?.peakTemperature.toFixed(1)??'—'} °C</td></tr>)}</tbody></table></div><p className="helper-text">¹ Over each scenario’s chosen horizon, conditional on repair success. ² Air-temperature degree-hours above the user’s threshold; a planning indicator, not a validated health or comfort index. Costs and occupancy are assumptions. Only the six most recent scenarios are plotted.</p></div>;
}
